apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dslapp-scheduler
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["dsl.test.com"]
  resources: ["dslapps"]
  verbs: ["get", "watch", "list", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dslapp-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dslapp-scheduler
subjects:
- kind: ServiceAccount
  name: dslapp-scheduler
  namespace: kube-system
