apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: test/metrics-collector:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: metrics-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
spec:
  selector:
    app: metrics-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
