apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-database-service
  template:
    metadata:
      labels:
        app: order-database-service
    spec:
      containers:
      - name: order-database-service
        image: order_database_service:latest
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: order-database-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-database-service
spec:
  selector:
    app: order-database-service
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051