apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dslapps.test.com
spec:
  group: test.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            app:
              type: string
            minPods:
              type: integer
            maxPods:
              type: integer
            cpuLimit:
              type: integer
            gpuLimit:
              type: integer
            freePods:
              type: integer
            memoryLimit:
              type: integer
  scope: Namespaced
  names:
    plural: dslapps
    singular: dslapp
    kind: DSLApp
    shortNames:
      - dsl