apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: system-node-critical
value: 1000000000
globalDefault: false
description: "This priority class is used for system-critical Pods."
