apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dslapp-operator
rules:
  - apiGroups: ["*"]
    resources: ["dslapps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dslapp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dslapp-operator
subjects:
  - kind: ServiceAccount
    name: dslapp-operator
